name: Run E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Show current directory and files (debug)
        run: |
          pwd
          ls -la
          ls -la src/test/resources

      - name: Run Maven tests with explicit testng.xml path
        run: mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml
